name: Depl;oying ASP.net to IIS on Azure Windows Server


on:
  push:
    branches:
      - main
    workflow_dispatch:


jobs:
  build-ASPdotnet-app:
    name: Build ASPdotnet Application
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Verify dotnet Version
        run: dotnet --version