name: Depl;oying ASP.net to IIS on Azure Windows Server


on:
  push:
    branches:
      - main
    workflow_dispatch:


jobs:
  build-ASPdotnet-app:
    name: Build ASPdotnet Application
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo in the github
        uses: actions/checkout@v3.3.0

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0

      - name: Verify dotnet Version
        run: dotnet --version

      - name: Publish ASPdotnet Application
        run: dotnet publish -o output

      - name: Verify the publish command
        run: ls 

      - name: Upload the output folder
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./output/*

    - name: Verify the file uploaded or not
      run: ls output/*


